server:
  port: 18500
spring:
  application:
    name: mall-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: mall-auth-service
          uri: lb://mall-auth-service
          predicates:
            - Path=/api/mall/auth/**
        - id: mall-user-service
          uri: lb://mall-user-service
          predicates:
            - Path=/api/mall/user/**
        - id: mall-search
          uri: lb://mall-search
          predicates:
            - Path=/mall-search/**
        - id: mall-product
          uri: lb://mall-product-service
          predicates:
            - Path=/api/mall/product/**
        - id: mall-order
          uri: lb://mall-order-service
          predicates:
            - Path=/api/mall/order/**, /api/mall/cart/**


#          filters:
#            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 10.10.0.14:8848
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/mall-auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    host: 39.102.83.104 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6699 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
secure:
  ignore:
    urls: #配置白名单路径
      - /doc.html
      - /api/mall/product/**
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always



logging:
  level:
    com.alibaba.nacos.client.*: WARN
