server:
  port: 28100

spring:
  application:
    name: mall-gateway-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.10.0.18:3306/mall?&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    #设置返回json数据null字段不显示
    default-property-inclusion: non_null
  redis:
    host: 39.102.83.104 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6699 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
  rabbitmq:
    host: 39.102.83.104
    port: 15672
    virtual-host: /mall
    username: guest
    password: guest
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.0.14:8848

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.shepherd.springcloudproduct.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx

aliyun-sms:
  accessKeyId: LTAI4GHpv2y35PBVWUt42fJ6
  accessSecret: VoF8212psWmcsb424bKVeg7eMZkKzA
  signName: shepherd
  templateCode: SMS_193518103
  expireTime: 10

#swagger
swagger-web:
  api-title: "Shepherd-mall Restful Apis"
  api-description: "Shepherd-mall swagger-ui"
  contact-name: "shepherd"
  contact-url:  "https://github.com/ICoder0"
  contact-email: "1059959730@qq.com"
  scan-package: "com.shepherd.malluser.api.controller"


secure:
  ignore:
    urls: "http://127.0.0.1/api/mall/product/*, http://127.0.0.1/api/mall/search/*"






