server:
  port: 18100

spring:
  application:
    name: mall-pay-service
  web:
    base-path: /mall/pay/api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.10.0.18:3306/mall_pay?&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    host: 10.10.0.14
    port: 6379
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  freemarker:
    suffix: .ftl
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.0.14:8848

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.shepherd.springcloudproduct.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx

aliyun-sms:
  accessKeyId: LTAI4GHpv2y35PBVWUt42fJ6
  accessSecret: VoF8212psWmcsb424bKVeg7eMZkKzA
  signName: shepherd
  templateCode: SMS_193518103
  expireTime: 10

wx:
  appId: wxd898fcb01713c658
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  notifyUrl: http://shepherd.natapp1.cc/api/mall/pay/notify
  returnUrl: http://127.0.0.1

alipay:
  appId: 2016102200741157
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC2G7j1z+t1VFVTDKbeQaiWL6oVNH2WoAOVy0EBDrqh8sgSR9gw7T22jQE70uBkU6l/B7htLRqa23L8IkP6ioimNXy2EG9Q6gqSJNZs3gJUUahfUXlyKZZIQovCE984X2iCtQOi7ZSxIZ57F3AIm4ezIJYozzZP38lpYlLLebf/O/kIsBGOkkSgEX34ymqcrnE7EtBk6B7+rv7CcRaJKXAIiW2FVQ2sqeuPdNk5YHqE99+4bS/QX/5+kOM0XSz/NrhaDWnW2Mka8zIUhMSp8CtjE1CrmlL9stEwiRYZJgc202kMOr0BUPlM1Gkm5lDgzlDwGzXcC0AyjNj09AW2+do3AgMBAAECggEABuhqTbjDX8IBMpNKSSgIcxn/w6ooEWykdiwtnRKn9bi16iubgc+eBay3nUNUi7m4tj7euhV56uHkLLhIB9r1cAibYHSjJFicagrHr32EbRpj3qnCh5gYQUl077m9P/AukLa5GpcUituRnW24LDtqHFtiFs41azY796lpJprJZf8Z/S4jLVZ0EUsoKQfyWTHAaKgv28TpLhe40HvVPXg4cf4YEBo++nXOKllQtApWQlfQbNAL06u2CTgYXQIVAoGzlM9gdHTW3IPJST5xRrfGYAjciZBtAkhMfGYYigtPhDLfxkG0rquRhzj4T9SD3HgfdUZ5Jl7zVf3l76Tg/t/loQKBgQDkWkjXyiJI/lzrxEYumUdUzS8uCRAtHm/TyjZRyi76RjTJCXjOpYC9uF3IfwQe0zIoLN8rHEQ9SLCFof6cNTnEfA7J9ZDyouQm3LIkZJ6KBHcR3SKbYy2s8jP1bLDAfh+yP4ANvIopnLxHndSQEwZa8PAzcYxa5UDwcF0PwC8ZSQKBgQDMKBvPV/AlrBU4LyaW7VsAK+w7Lj+lxp2bZiRZGq7iRkqLixGuybTAQdPQ8uQM80IIoE65j0pUk8cThVk1fbZNMr+tsjCiop/ZeirtLYanXKEhGvusnXmHcO/obxl3YIOGFAro5Zmv47y8VHdR5kqK9oZosBj6n8G4k/PHpmDXfwKBgQCIpurej+0yh12uDZf+POXt/pgUUYInrgY31NPq4DZ6uVbPU+bCq1I+tr0Qxcn+dF6Yojmu/8xqbDyOy+GlM0jtp1vmShlCym4EP6AvnTMu3vsuaopSOOjVjV/AqBmiKBfpwIxuK/z2aABYT0AsM+Zit7rW3kWjA3x4JpXaXiURWQKBgCVEMQdhOwH1bo4p9TZZr2HRoraO06l0HvLt6zakq0W8pQDh6uFoCmmJ2ptqqvw+L1CZyqUOpffYXd+PWOBtyShAWkLfowcc/mbZaRqQU+MbAoKjhUtWF4gEspZQKWrkID4KTI+E0dAMlzgdhwZZLkQ9if10H6soHFmQEFDiaw0LAoGBAMNY1uH9s//q+rwp9P7r3jn7wjjjdz6ci57A2PtRwWpzABCGwTa9IMdqc4uq76zLIUJzU6x/clamAmr/4cXWGK3Ctbpx7jFFVdDfEWIJf7uUa9WxohKgySNM13pL5VX/U06MQg4gJGxbGlYP8yv0YmtfWgilbqNFveUl9stp2JaZ
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnB+/r+d/ZpV+RY2VngYhIPuo0Mw972yzyzmlJXrYi9Tv8QGlOL4z1zb190N9u+1XSpQPiJFwHHyz9VpODNxW3DDpLs/KPFF6d3me3VyXFD2XRPwHjMqXDisCtxIDSh0J3f6qQQqB7vYOcF/0+ZwqWLu2Y/hQAc82ceYEKDedkmB2qb4/v07FiT4rSOUtN8+ZlSF+2KrIDkhyR7oSDvL7fMs20ISHjagQtwjETCYVd1612AQHERzQXq6PqT2z5Eru46daw7kiGh/yOED/NcC0P7t1rhprsfjqkjAabEKBBRrdq2KPAtaN3i6pjH5ia+m5LBZ0NwURVPnuOUTKJ/7TMwIDAQAB
  notifyUrl: http://39q70t4507.qicp.vip/api/mall/pay/notify
  returnUrl: http://127.0.0.1

micro-server:
  mall-order: mall-order-service








